-- 1) Apaga a tabela antiga (e todo o conteúdo)
DROP TABLE "SYSTEM"."TB_PACIENTE" PURGE;

CREATE TABLE "SYSTEM"."TB_PACIENTE" (
  "CD_PACIENTE"    NUMBER GENERATED BY DEFAULT AS IDENTITY
                     MINVALUE 1
                     MAXVALUE 9999999999999999999999999999
                     INCREMENT BY 1
                     START WITH 1
                     CACHE 20
                     NOORDER
                     NOCYCLE
                     NOKEEP
                     NOSCALE
                     NOT NULL,
  "NR_RESPONSAVEL" VARCHAR2(20 BYTE),
  "NM_RESPONSAVEL" VARCHAR2(100 BYTE),
  "NM_PACIENTE"    VARCHAR2(100 BYTE) NOT NULL,
  "PRECO_FONO"     NUMBER(10,2),
  "HORAS_FONO"     NUMBER(5,0),
  "TOTAL_FONO"     NUMBER(12,2),
  "REEMBOLSO_FONO" NUMBER(10,2),
  "NF_FONO"        NUMBER(5,0),
  "PRECO_TO"       NUMBER(10,2),
  "HORAS_TO"       NUMBER(5,0),
  "TOTAL_TO"       NUMBER(12,2),
  "REEMBOLSO_TO"   NUMBER(10,2),
  "NF_TO"          NUMBER(5,0),
  "PRECO_ABA"      NUMBER(10,2),
  "REEMBOLSO_ABA"  NUMBER(10,2),
  "NF_ABA"         NUMBER(5,0),
  CONSTRAINT PK_TB_PACIENTE PRIMARY KEY ("CD_PACIENTE")
);

SELECT
  cd_paciente,
  nr_responsavel,
  nm_responsavel,
  nm_paciente,
  preco_fono,  horas_fono,  total_fono,  reembolso_fono,  nf_fono,
  preco_to,    horas_to,    total_to,    reembolso_to,    nf_to,
  preco_aba,   reembolso_aba, nf_aba
FROM tb_paciente;

ALTER TABLE "SYSTEM"."TB_PACIENTE"
  MODIFY ("NR_RESPONSAVEL" VARCHAR2(20 BYTE));
