CREATE SEQUENCE seq_paciente
START WITH 1
INCREMENT BY 1;

DROP TABLE tb_paciente;

CREATE TABLE tb_paciente (
    cd_paciente      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_paciente      VARCHAR2(100) NOT NULL,
    preco_fono       NUMBER(10,2),
    horas_fono       NUMBER(5),
    total_fono       NUMBER(12,2),
    reembolso_fono   NUMBER(10,2),
    nf_fono          NUMBER(5),
    preco_to         NUMBER(10,2),
    horas_to         NUMBER(5),
    total_to         NUMBER(12,2),
    reembolso_to     NUMBER(10,2),
    nf_to            NUMBER(5),
    preco_aba        NUMBER(10,2),
    reembolso_aba    NUMBER(10,2),
    nf_aba           NUMBER(5)
);


