CREATE TABLE tb_paciente (
  cd_paciente       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nr_responsavel    NUMBER(14),
  nm_responsavel    VARCHAR2(120),
  nm_paciente       VARCHAR2(120),

  preco_fono        NUMBER(10,2),
  horas_fono        NUMBER(5),
  total_fono        NUMBER(12,2),
  reembolso_fono    NUMBER(10,2),
  nf_fono           NUMBER(6),

  preco_to          NUMBER(10,2),
  horas_to          NUMBER(5),
  total_to          NUMBER(12,2),
  reembolso_to      NUMBER(10,2),
  nf_to             NUMBER(6),

  preco_aba         NUMBER(10,2),
  reembolso_aba     NUMBER(10,2),
  nf_aba            NUMBER(6)
);